/**
 * Colony Context — a shared context file that all Colony-launched sessions reference.
 * Gives every Claude session awareness of the broader Colony state:
 * active sessions, repos, PRs, agents, task queues, handoffs, memory files.
 *
 * Written to ~/.claude-colony/colony-context.md
 * Updated on demand (before launching prompts) and periodically.
 */

import { promises as fsp } from 'fs'
import { join, basename } from 'path'
import { app } from 'electron'
import { getAllInstances } from './instance-manager'
import { scanAgents } from './agent-scanner'
import { getRepoContext } from './repo-config-loader'
import { getRepos } from './github'
import { getPersonaList } from './persona-manager'
import { readPersonaMemory } from './persona-memory'
import { listEnvironments } from './env-manager'
import { getPipelineList } from './pipeline-engine'

import { colonyPaths } from '../shared/colony-paths'

const COLONY_DIR = colonyPaths.root
const CONTEXT_PATH = colonyPaths.colonyContext

/** Check if a path exists (async replacement for existsSync). */
async function pathExists(p: string): Promise<boolean> {
  try { await fsp.stat(p); return true } catch { return false }
}

export async function updateColonyContext(): Promise<string> {
  await fsp.mkdir(COLONY_DIR, { recursive: true })

  const lines: string[] = [
    '# Colony Context',
    '',
    `_Auto-generated by Claude Colony. Last updated: ${new Date().toISOString()}_`,
    '',
    'This file describes the current state of the Colony workspace. Read it for awareness of what else is happening across sessions.',
    '',
  ]

  // Active sessions
  try {
    const instances = await getAllInstances()
    const running = instances.filter((i) => i.status === 'running')
    const stopped = instances.filter((i) => i.status !== 'running')

    lines.push('## Active Sessions', '')
    if (running.length === 0) {
      lines.push('No active sessions.', '')
    } else {
      for (const inst of running) {
        const activity = inst.activity === 'busy' ? '(busy)' : '(waiting)'
        const cli = inst.cliBackend === 'cursor-agent' ? 'Cursor agent' : 'Claude Code'
        lines.push(`- **${inst.name}** [${cli}] ${activity} — ${inst.workingDirectory}`)
        if (inst.parentId) lines.push(`  - Child of another session`)
        if (inst.childIds.length > 0) lines.push(`  - Has ${inst.childIds.length} child session(s)`)
      }
      lines.push('')
    }

    if (stopped.length > 0) {
      lines.push(`${stopped.length} stopped session(s).`, '')
    }
  } catch { /* */ }

  // GitHub repos and PR summary
  try {
    const repos = await getRepos()
    if (repos.length > 0) {
      lines.push('## GitHub Repositories', '')
      for (const repo of repos) {
        lines.push(`- ${repo.owner}/${repo.name}${repo.localPath ? ` (local: ${repo.localPath})` : ''}`)
      }
      lines.push('')
    }

    // PR context file reference
    const prContextPath = join(COLONY_DIR, 'pr-workspace', 'pr-context.md')
    if (await pathExists(prContextPath)) {
      lines.push(`**PR data:** Read ${prContextPath} for full PR details, descriptions, and comment file references.`, '')
    }
  } catch { /* */ }

  // PR Memory reference
  const prMemoryPath = join(COLONY_DIR, 'pr-workspace', 'pr-memory.md')
  if (await pathExists(prMemoryPath)) {
    lines.push(`**PR Memory:** ${prMemoryPath} — persistent knowledge from PR reviews and discussions.`, '')
  }

  // Environments
  try {
    const envs = await listEnvironments()
    if (envs.length > 0) {
      lines.push('## Environments', '')
      for (const env of envs) {
        const svcSummary = env.services.map(s => `${s.name}(${s.status})`).join(', ')
        lines.push(`- **${env.displayName || env.name}** [${env.status}] — branch: ${env.branch}, services: ${svcSummary || 'none'}`)
        if (env.paths.root) lines.push(`  Path: ${env.paths.root}`)
      }
      lines.push('')
    }
  } catch { /* */ }

  // Pipelines
  try {
    const pipelines = getPipelineList()
    if (pipelines.length > 0) {
      lines.push('## Pipelines', '')
      for (const p of pipelines) {
        const status = p.enabled ? 'enabled' : 'disabled'
        const lastFired = p.lastFiredAt ? `, last fired: ${p.lastFiredAt.slice(0, 16)}` : ''
        const trigger = p.cron ? `cron: ${p.cron}` : `${p.triggerType} every ${p.interval}s`
        lines.push(`- **${p.name}** [${status}] — ${trigger}, fired ${p.fireCount}x${lastFired}`)
        if (p.description) lines.push(`  ${p.description}`)
        lines.push(`  File: ${join(COLONY_DIR, 'pipelines', p.fileName)}`)
        if (p.outputsDir) lines.push(`  Outputs: ${p.outputsDir}`)
      }
      lines.push('')
    }
  } catch { /* */ }

  // Agents
  try {
    const agents = scanAgents()
    if (agents.length > 0) {
      lines.push('## Agents', '')
      for (const agent of agents) {
        lines.push(`- **${agent.name}** (${agent.scope}) — ${agent.description.slice(0, 80)}`)
        lines.push(`  File: ${agent.filePath}`)
      }
      lines.push('')
    }
  } catch { /* */ }

  // Personas
  try {
    const personas = getPersonaList()
    if (personas.length > 0) {
      lines.push('## Personas', '')
      for (const p of personas) {
        const status = p.activeSessionId ? 'running' : p.enabled ? 'enabled' : 'disabled'
        lines.push(`- **${p.name}** (${status}) — model: ${p.model}, runs: ${p.runCount}${p.schedule ? `, schedule: ${p.schedule}` : ''}`)
        lines.push(`  File: ${p.filePath}`)
        // Include active (non-done) situations from structured sidecar
        try {
          const mem = readPersonaMemory(p.id)
          const active = mem.activeSituations.filter(s => s.status !== 'done')
          if (active.length > 0) {
            for (const s of active.slice(0, 5)) {
              lines.push(`  - [${s.status.toUpperCase()}] ${s.text.slice(0, 120)}`)
            }
            if (active.length > 5) lines.push(`  - ... and ${active.length - 5} more`)
          }
        } catch { /* no sidecar yet */ }
      }
      lines.push('')
    }
  } catch { /* */ }

  // Task queues
  try {
    const queueDir = join(COLONY_DIR, 'task-queues')
    if (await pathExists(queueDir)) {
      const allFiles = await fsp.readdir(queueDir)
      const files = allFiles.filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
      if (files.length > 0) {
        lines.push('## Task Queues', '')
        for (const f of files) {
          // Extract output paths from task prompts
          const outputDirs = new Set<string>()
          try {
            const content = await fsp.readFile(join(queueDir, f), 'utf-8')
            const matches = content.match(/~\/\.claude-colony\/outputs\/[^\s"']+/g)
            if (matches) {
              for (const m of matches) {
                // Get the directory (strip the filename)
                const dir = m.replace(/\/[^/]+\.\w+$/, '')
                outputDirs.add(dir.replace('~', process.env.HOME || '~'))
              }
            }
          } catch { /* */ }
          lines.push(`- ${f} — ${join(queueDir, f)}`)
          for (const dir of outputDirs) {
            lines.push(`  Outputs: ${dir}/`)
          }
        }
        lines.push('')
      }
    }
  } catch { /* */ }

  // Active Specs
  try {
    const specsDir = colonyPaths.specs
    if (await pathExists(specsDir)) {
      const allFiles = await fsp.readdir(specsDir)
      const specFiles = allFiles.filter(f => f.endsWith('.md'))
      if (specFiles.length > 0) {
        const activeSpecs: Array<{ name: string; title: string; updatedAt: string }> = []
        for (const f of specFiles) {
          const filePath = join(specsDir, f)
          const content = await fsp.readFile(filePath, 'utf-8')
          // Parse frontmatter for status
          const fmMatch = content.match(/^---\n([\s\S]*?)\n---/)
          if (fmMatch) {
            const statusMatch = fmMatch[1].match(/^status:\s*(.+)$/m)
            const status = statusMatch ? statusMatch[1].trim() : 'active'
            if (status !== 'active') continue
            const titleMatch = fmMatch[1].match(/^title:\s*(.+)$/m)
            const title = titleMatch ? titleMatch[1].trim().replace(/^["']|["']$/g, '') : f.replace(/\.md$/, '')
            const stat = await fsp.stat(filePath)
            activeSpecs.push({ name: f.replace(/\.md$/, ''), title, updatedAt: stat.mtime.toISOString().slice(0, 16) })
          }
        }
        if (activeSpecs.length > 0) {
          lines.push('## Active Specs', '')
          for (const s of activeSpecs) {
            lines.push(`- **${s.title}** (${s.name}) — last updated: ${s.updatedAt}`)
          }
          lines.push('')
        }
      }
    }
  } catch { /* */ }

  // Handoffs
  try {
    const handoffDir = join(COLONY_DIR, 'handoffs')
    if (await pathExists(handoffDir)) {
      const allFiles = await fsp.readdir(handoffDir)
      const files = allFiles.filter((f) => f.endsWith('.md'))
      if (files.length > 0) {
        lines.push('## Recent Handoffs', '')
        for (const f of files.slice(-10)) {
          lines.push(`- ${join(handoffDir, f)}`)
        }
        lines.push('')
      }
    }
  } catch { /* */ }

  // Key paths
  lines.push('## Key Paths', '')
  lines.push(`- Colony config: ${COLONY_DIR}`)
  lines.push(`- Outputs: ${join(COLONY_DIR, 'outputs')}`)
  lines.push(`- PR workspace: ${join(COLONY_DIR, 'pr-workspace')}`)
  lines.push(`- Task queues: ${join(COLONY_DIR, 'task-queues')}`)
  lines.push(`- Handoffs: ${join(COLONY_DIR, 'handoffs')}`)
  lines.push(`- This file: ${CONTEXT_PATH}`)
  lines.push('')

  const content = lines.join('\n')
  await fsp.writeFile(CONTEXT_PATH, content, 'utf-8')
  return CONTEXT_PATH
}

export function getColonyContextPath(): string {
  return CONTEXT_PATH
}

/**
 * Returns a string to append to any prompt that makes it Colony-aware.
 */
export async function getColonyContextInstruction(workingDirectory?: string): Promise<string> {
  let instruction = `\n\nA Colony context file exists at ${CONTEXT_PATH}. It describes all active sessions, repos, agents, task queues, and handoffs in this workspace. Read it if you need broader context about what else is happening.`

  // Append repo-specific context if .colony/context.md exists
  if (workingDirectory) {
    try {
      const repoContext = await getRepoContext(workingDirectory)
      if (repoContext) {
        instruction += `\n\n--- Project Context ---\n${repoContext}`
      }
    } catch { /* repo config loader not available */ }
  }

  return instruction
}
