/**
 * Colony Context — a shared context file that all Colony-launched sessions reference.
 * Gives every Claude session awareness of the broader Colony state:
 * active sessions, repos, PRs, agents, task queues, handoffs, memory files.
 *
 * Written to ~/.claude-colony/colony-context.md
 * Updated on demand (before launching prompts) and periodically.
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, mkdirSync } from 'fs'
import { join, basename } from 'path'
import { app } from 'electron'
import { getAllInstances } from './instance-manager'
import { scanAgents } from './agent-scanner'

const COLONY_DIR = join(app.getPath('home'), '.claude-colony')
const CONTEXT_PATH = join(COLONY_DIR, 'colony-context.md')

export async function updateColonyContext(): Promise<string> {
  if (!existsSync(COLONY_DIR)) mkdirSync(COLONY_DIR, { recursive: true })

  const lines: string[] = [
    '# Colony Context',
    '',
    `_Auto-generated by Claude Colony. Last updated: ${new Date().toISOString()}_`,
    '',
    'This file describes the current state of the Colony workspace. Read it for awareness of what else is happening across sessions.',
    '',
  ]

  // Active sessions
  try {
    const instances = await getAllInstances()
    const running = instances.filter((i) => i.status === 'running')
    const stopped = instances.filter((i) => i.status !== 'running')

    lines.push('## Active Sessions', '')
    if (running.length === 0) {
      lines.push('No active sessions.', '')
    } else {
      for (const inst of running) {
        const activity = inst.activity === 'busy' ? '(busy)' : '(waiting)'
        const cli = inst.cliBackend === 'cursor-agent' ? 'Cursor agent' : 'Claude Code'
        lines.push(`- **${inst.name}** [${cli}] ${activity} — ${inst.workingDirectory}`)
        if (inst.parentId) lines.push(`  - Child of another session`)
        if (inst.childIds.length > 0) lines.push(`  - Has ${inst.childIds.length} child session(s)`)
      }
      lines.push('')
    }

    if (stopped.length > 0) {
      lines.push(`${stopped.length} stopped session(s).`, '')
    }
  } catch { /* */ }

  // GitHub repos and PR summary
  try {
    const configPath = join(COLONY_DIR, 'github.json')
    if (existsSync(configPath)) {
      const config = JSON.parse(readFileSync(configPath, 'utf-8'))
      const repos = config.repos || []
      if (repos.length > 0) {
        lines.push('## GitHub Repositories', '')
        for (const repo of repos) {
          lines.push(`- ${repo.owner}/${repo.name}${repo.localPath ? ` (local: ${repo.localPath})` : ''}`)
        }
        lines.push('')
      }
    }

    // PR context file reference
    const prContextPath = join(COLONY_DIR, 'pr-workspace', 'pr-context.md')
    if (existsSync(prContextPath)) {
      lines.push(`**PR data:** Read ${prContextPath} for full PR details, descriptions, and comment file references.`, '')
    }
  } catch { /* */ }

  // PR Memory reference
  const prMemoryPath = join(COLONY_DIR, 'pr-workspace', 'pr-memory.md')
  if (existsSync(prMemoryPath)) {
    lines.push(`**PR Memory:** ${prMemoryPath} — persistent knowledge from PR reviews and discussions.`, '')
  }

  // Agents
  try {
    const agents = scanAgents()
    if (agents.length > 0) {
      lines.push('## Agents', '')
      for (const agent of agents) {
        lines.push(`- **${agent.name}** (${agent.scope}) — ${agent.description.slice(0, 80)}`)
        lines.push(`  File: ${agent.filePath}`)
      }
      lines.push('')
    }
  } catch { /* */ }

  // Task queues
  try {
    const queueDir = join(COLONY_DIR, 'task-queues')
    if (existsSync(queueDir)) {
      const files = readdirSync(queueDir).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'))
      if (files.length > 0) {
        lines.push('## Task Queues', '')
        for (const f of files) {
          lines.push(`- ${f} — ${join(queueDir, f)}`)
        }
        lines.push('')
      }
    }
  } catch { /* */ }

  // Handoffs
  try {
    const handoffDir = join(COLONY_DIR, 'handoffs')
    if (existsSync(handoffDir)) {
      const files = readdirSync(handoffDir).filter((f) => f.endsWith('.md'))
      if (files.length > 0) {
        lines.push('## Recent Handoffs', '')
        for (const f of files.slice(-10)) {
          lines.push(`- ${join(handoffDir, f)}`)
        }
        lines.push('')
      }
    }
  } catch { /* */ }

  // Key paths
  lines.push('## Key Paths', '')
  lines.push(`- Colony config: ${COLONY_DIR}`)
  lines.push(`- PR workspace: ${join(COLONY_DIR, 'pr-workspace')}`)
  lines.push(`- Task queues: ${join(COLONY_DIR, 'task-queues')}`)
  lines.push(`- Handoffs: ${join(COLONY_DIR, 'handoffs')}`)
  lines.push(`- This file: ${CONTEXT_PATH}`)
  lines.push('')

  const content = lines.join('\n')
  writeFileSync(CONTEXT_PATH, content, 'utf-8')
  return CONTEXT_PATH
}

export function getColonyContextPath(): string {
  return CONTEXT_PATH
}

/**
 * Returns a string to append to any prompt that makes it Colony-aware.
 */
export function getColonyContextInstruction(): string {
  return `\n\nA Colony context file exists at ${CONTEXT_PATH}. It describes all active sessions, repos, agents, task queues, and handoffs in this workspace. Read it if you need broader context about what else is happening.`
}
