/**
 * Generates a CLAUDE.md file for environment instances so pipeline/persona
 * sessions automatically understand the environment context (repos, services,
 * ports, paths, resources) when they launch inside a worktree.
 *
 * Written to:
 *  - Each mounted worktree bundle dir (parent of repo checkouts — Claude CLI walks up from cwd)
 *  - The environment root dir (for sessions that use env root as cwd)
 */

import fsp from 'node:fs/promises'
import path from 'node:path'
import type { InstanceManifest } from '../daemon/env-protocol'
import { colonyPaths } from '../shared/colony-paths'

function buildClaudeMd(manifest: InstanceManifest): string {
  const lines: string[] = []
  const name = manifest.displayName || manifest.name

  lines.push(`# Environment: ${name}`)
  lines.push('')

  // Summary line
  const parts: string[] = [`Instance: ${manifest.name}`]
  if (manifest.git?.branch) parts.push(`Branch: ${manifest.git.branch}`)
  if (manifest.git?.baseBranch) parts.push(`Base: ${manifest.git.baseBranch}`)
  lines.push(parts.join(' | '))
  lines.push('')

  // Paths
  const pathEntries = Object.entries(manifest.paths).filter(([, v]) => v)
  if (pathEntries.length > 0) {
    lines.push('## Paths')
    lines.push('')
    lines.push('| Key | Path |')
    lines.push('|-----|------|')
    for (const [key, val] of pathEntries) {
      lines.push(`| ${key} | ${val} |`)
    }
    lines.push('')
  }

  // Services
  const svcEntries = Object.entries(manifest.services)
  if (svcEntries.length > 0) {
    lines.push('## Services')
    lines.push('')
    lines.push('| Service | Port | Command |')
    lines.push('|---------|------|---------|')
    for (const [svcName, svc] of svcEntries) {
      const port = svc.port ?? ''
      const cmd = svc.command?.slice(0, 80) || ''
      lines.push(`| ${svcName} | ${port} | \`${cmd}\` |`)
    }
    lines.push('')
  }

  // Ports
  const portEntries = Object.entries(manifest.ports)
  if (portEntries.length > 0) {
    lines.push('## Ports')
    lines.push('')
    for (const [key, port] of portEntries) {
      lines.push(`- **${key}**: ${port}`)
    }
    lines.push('')
  }

  // URLs
  if (manifest.urls) {
    const urlEntries = Object.entries(manifest.urls).filter(([, v]) => v)
    if (urlEntries.length > 0) {
      lines.push('## URLs')
      lines.push('')
      for (const [key, url] of urlEntries) {
        lines.push(`- **${key}**: ${url}`)
      }
      lines.push('')
    }
  }

  // Resources
  if (manifest.resources) {
    const resEntries = Object.entries(manifest.resources)
    if (resEntries.length > 0) {
      lines.push('## Resources')
      lines.push('')
      for (const [key, res] of resEntries) {
        const details = Object.entries(res)
          .filter(([k]) => k !== 'type')
          .map(([k, v]) => `${k}: ${v}`)
          .join(', ')
        lines.push(`- **${key}** (${res.type || 'unknown'}): ${details}`)
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('_Auto-generated by Colony. Regenerated on worktree swap and config changes._')
  lines.push('')

  return lines.join('\n')
}

/**
 * Generate and write CLAUDE.md for an environment instance.
 * Fire-and-forget — failures are logged but never block the caller.
 */
export async function generateEnvClaudeMd(manifest: InstanceManifest): Promise<void> {
  const content = buildClaudeMd(manifest)
  const writes: Promise<void>[] = []

  // Write to environment root dir
  if (manifest.paths.root) {
    writes.push(
      fsp.writeFile(path.join(manifest.paths.root, 'CLAUDE.md'), content, 'utf-8')
        .catch(() => {})
    )
  }

  // Write to worktree bundle dir (parent of repo checkouts)
  if (manifest.activeWorktreeId) {
    const wtDir = colonyPaths.worktreeDir(manifest.activeWorktreeId)
    writes.push(
      fsp.writeFile(path.join(wtDir, 'CLAUDE.md'), content, 'utf-8')
        .catch(() => {})
    )
  }

  await Promise.all(writes)
}
