/**
 * Generates a CLAUDE.md file for environment instances so pipeline/persona
 * sessions automatically understand the environment context (repos, services,
 * ports, paths, resources) when they launch inside a worktree.
 *
 * Written to:
 *  - Each mounted worktree bundle dir (parent of repo checkouts — Claude CLI walks up from cwd)
 *  - The environment root dir (for sessions that use env root as cwd)
 */

import { promises as fsp } from 'fs'
import path from 'node:path'
import type { InstanceManifest } from '../daemon/env-protocol'
import { colonyPaths } from '../shared/colony-paths'

/**
 * Stable delimiter markers — treat as a forever contract.
 * Changing them orphans the auto-section in existing user files.
 */
const AUTO_START =
  '<!-- COLONY:AUTO-START \u2014 do not edit between these markers. Your edits outside this block are preserved. -->'
const AUTO_END = '<!-- COLONY:AUTO-END -->'

function buildClaudeMd(manifest: InstanceManifest): string {
  const lines: string[] = []
  const name = manifest.displayName || manifest.name

  lines.push(`# Environment: ${name}`)
  lines.push('')

  // Summary line
  const parts: string[] = [`Instance: ${manifest.name}`]
  if (manifest.git?.branch) parts.push(`Branch: ${manifest.git.branch}`)
  if (manifest.git?.baseBranch) parts.push(`Base: ${manifest.git.baseBranch}`)
  lines.push(parts.join(' | '))
  lines.push('')

  // Paths
  const pathEntries = Object.entries(manifest.paths).filter(([, v]) => v)
  if (pathEntries.length > 0) {
    lines.push('## Paths')
    lines.push('')
    lines.push('| Key | Path |')
    lines.push('|-----|------|')
    for (const [key, val] of pathEntries) {
      lines.push(`| ${key} | ${val} |`)
    }
    lines.push('')
  }

  // Services
  const svcEntries = Object.entries(manifest.services)
  if (svcEntries.length > 0) {
    lines.push('## Services')
    lines.push('')
    lines.push('| Service | Port | Command |')
    lines.push('|---------|------|---------|')
    for (const [svcName, svc] of svcEntries) {
      const port = svc.port ?? ''
      const cmd = svc.command?.slice(0, 80) || ''
      lines.push(`| ${svcName} | ${port} | \`${cmd}\` |`)
    }
    lines.push('')
  }

  // Ports
  const portEntries = Object.entries(manifest.ports)
  if (portEntries.length > 0) {
    lines.push('## Ports')
    lines.push('')
    for (const [key, port] of portEntries) {
      lines.push(`- **${key}**: ${port}`)
    }
    lines.push('')
  }

  // URLs
  if (manifest.urls) {
    const urlEntries = Object.entries(manifest.urls).filter(([, v]) => v)
    if (urlEntries.length > 0) {
      lines.push('## URLs')
      lines.push('')
      for (const [key, url] of urlEntries) {
        lines.push(`- **${key}**: ${url}`)
      }
      lines.push('')
    }
  }

  // Resources
  if (manifest.resources) {
    const resEntries = Object.entries(manifest.resources)
    if (resEntries.length > 0) {
      lines.push('## Resources')
      lines.push('')
      for (const [key, res] of resEntries) {
        const details = Object.entries(res)
          .filter(([k]) => k !== 'type')
          .map(([k, v]) => `${k}: ${v}`)
          .join(', ')
        lines.push(`- **${key}** (${res.type || 'unknown'}): ${details}`)
      }
      lines.push('')
    }
  }

  lines.push('---')
  lines.push('_Auto-generated by Colony. Regenerated on worktree swap and config changes._')

  // Wrap in stable markers. No trailing newline — writeWithMerge manages separators.
  return `${AUTO_START}\n${lines.join('\n')}\n${AUTO_END}`
}

/**
 * Merge a freshly generated auto-block into existing CLAUDE.md content.
 *
 * - Has markers → replace block between markers, preserve content before/after.
 * - No markers  → prepend generated block above existing content.
 */
function mergeClaudeMd(existing: string, generated: string): string {
  const startIdx = existing.indexOf(AUTO_START)
  const endIdx = existing.indexOf(AUTO_END)
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    return existing.slice(0, startIdx) + generated + existing.slice(endIdx + AUTO_END.length)
  }
  return generated + '\n\n' + existing
}

/**
 * Read-merge-write a CLAUDE.md at `filePath`.
 * - Missing file → write generated block as-is.
 * - Existing file → merge (preserving user edits outside the auto block).
 * - Content unchanged → skip write entirely.
 * Read errors (ENOENT etc.) are treated as "file doesn't exist".
 */
async function writeWithMerge(filePath: string, generated: string): Promise<void> {
  let existing: string | null = null
  try {
    existing = await fsp.readFile(filePath, 'utf-8')
  } catch {
    // Fall through — treat as missing file
  }
  const output = existing === null ? generated : mergeClaudeMd(existing, generated)
  if (output === existing) return
  await fsp.writeFile(filePath, output, 'utf-8')
}

/**
 * Generate and write CLAUDE.md for an environment instance.
 * Fire-and-forget — failures are logged but never block the caller.
 */
export async function generateEnvClaudeMd(manifest: InstanceManifest): Promise<void> {
  const generated = buildClaudeMd(manifest)
  const writes: Promise<void>[] = []

  // Write to environment root dir
  if (manifest.paths.root) {
    writes.push(writeWithMerge(path.join(manifest.paths.root, 'CLAUDE.md'), generated).catch(() => {}))
  }

  // Write to worktree bundle dir (parent of repo checkouts)
  if (manifest.activeWorktreeId) {
    const wtDir = colonyPaths.worktreeDir(manifest.activeWorktreeId)
    writes.push(writeWithMerge(path.join(wtDir, 'CLAUDE.md'), generated).catch(() => {}))
  }

  await Promise.all(writes)
}

/**
 * Regenerate CLAUDE.md for an environment and return the paths written.
 * Unlike generateEnvClaudeMd, errors are NOT swallowed — they surface to the caller.
 */
export async function regenerateEnvClaudeMdStrict(manifest: InstanceManifest): Promise<{ writtenPaths: string[] }> {
  const generated = buildClaudeMd(manifest)
  const writtenPaths: string[] = []

  if (manifest.paths.root) {
    const p = path.join(manifest.paths.root, 'CLAUDE.md')
    await writeWithMerge(p, generated)
    writtenPaths.push(p)
  }

  if (manifest.activeWorktreeId) {
    const wtDir = colonyPaths.worktreeDir(manifest.activeWorktreeId)
    const p = path.join(wtDir, 'CLAUDE.md')
    await writeWithMerge(p, generated)
    writtenPaths.push(p)
  }

  return { writtenPaths }
}

/**
 * Read the CLAUDE.md file for an environment from the specified target location.
 * Returns { exists: false } on ENOENT instead of throwing.
 */
export async function readEnvClaudeMd(
  manifest: InstanceManifest,
  target: 'root' | 'worktree',
): Promise<{ exists: boolean; content: string; path: string }> {
  let filePath: string
  if (target === 'worktree') {
    if (!manifest.activeWorktreeId) throw new Error('No active worktree for this environment')
    filePath = path.join(colonyPaths.worktreeDir(manifest.activeWorktreeId), 'CLAUDE.md')
  } else {
    if (!manifest.paths.root) throw new Error('No root path in manifest')
    filePath = path.join(manifest.paths.root, 'CLAUDE.md')
  }
  try {
    const content = await fsp.readFile(filePath, 'utf-8')
    return { exists: true, content, path: filePath }
  } catch (err: any) {
    if (err.code === 'ENOENT') return { exists: false, content: '', path: filePath }
    throw err
  }
}
